### ISSUE TITLE
timeout needed or it fails to find any packets

### ISSUE THREAD

**Issue by cholcombe973** [ebfull/pcap#23]
I'm not sure why but if I don't set a timeout on the Capture my code returns immediately without finding any packets.  I'm running this on ubuntu 14.04 64bit.  Is this behavior expected?

**Comment by ebfull** [comment]
pcap's timeout default is decided by pcap itself. I'm not sure what goes into that calculation, but apparently different platforms have different timeouts, perhaps interfaces as well.

I'm not even sure making our bindings have a default would be a good idea, since timeouts can apparently be interpreted differently on different platforms. Is there precedence for a default provided by other pcap bindings?

**Comment by cholcombe973** [comment]
So i ended up fixing my code with an infinite loop that keeps calling the .next() function on the capture interface.  I'm not sure if the other bindings have a timeout preference.  I agree it's prob best not to set it to anything by default in the library.
