### ISSUE TITLE
Mismatched types when trying the example

### ISSUE THREAD

**Issue by vlttnv** [ebfull/pcap#30]
Hello. I recently started learning Rust please bare with me.

I tried running the example:
```
let mut cap = Device::lookup().unwrap().open().unwrap();

    while let Some(packet) = cap.next() {
        println!("received packet: {:?}", packet);
    }
```

But I get the following error for `Some(packet)`:
```
error: mismatched types:
 expected `core::result::Result<pcap::Packet<'_>, pcap::Error>`,
    found `core::option::Option<_>`
(expected enum `core::result::Result`,
```

I am not very used to `Option` yet so I might be missing something obvious.

Thanks.

**Comment by ebfull** [comment]
Nice catch, some of the documentation is out of date. :( I recommend looking at [these examples](https://github.com/ebfull/pcap/tree/master/examples) instead of the ones in the documentation for now.

Try this instead:

```rust
let mut cap = Device::lookup().unwrap().open().unwrap();

while let Ok(packet) = cap.next() {
     println!("received packet: {:?}", packet);
}
```

The reason for the error is that I changed `cap.next()` at some point to return a `Result<...>` instead of an `Option<...>`. `Ok(Packet)` is the type variant of a successful result from `cap.next()`.

I will use your other ticket on documentation to address this, for now I'll close this. Thanks. :)
