### ISSUE TITLE
[ERROR] - Window can't not open default device

### ISSUE THREAD

**Issue by hieuit7** [ebfull/pcap#53]
I have an error, please help me!

i call this: 

`let mut cap = Capture::from_device(Device::lookup().unwrap())`

`Result::unwrap()` on an `Err` value: PcapError("Error opening adapter: The system cannot find the device specified. (20)"

**Comment by ebfull** [comment]
I believe that will fetch the default device from pcap's perspective, and I can't remember what it does when it can't find an appropriate device. You should use `Device::list` to list out all the devices available to you and go that route. It might also be possible that you don't have admin privileges or winpcap isn't installed or you haven't rebooted it since you installed it or something like that. (I don't have Windows so I don't know.)

**Comment by hieuit7** [comment]
I was tested with Device::list and get specify exactly device name and it working. I think it have a problem with string name from open device. When I have time, I will debug and fix this.

**Comment by aldanor** [comment]
Can this be closed now?

**Comment by aldanor** [comment]
It doesn't look like an issue with the crate, but rather with how `libpcap` behaves on Windows. Please reopen this if you feel there's anything we could fix.
