### ISSUE TITLE
Nightly build failure

### ISSUE THREAD

**Issue by palfrey** [ebfull/pcap#82]
I think this is due to the line saying `env: FLAGS="--features clippy,tokio"` when it should be `env: FLAGS="--features \"clippy tokio\""` (or something like that, modulo different escaping rules)

**Comment by Trolldemorted** [comment]
PR #86 mitigates this by fixing all tests without the `tokio` feature. Nevertheless we should get our separators correct.

**Comment by Wojtek242** [comment]
`env: FLAGS="--features \"clippy tokio\""` annoyingly doesn't actually work, because the `"` is combined with `clippy` and the build fails, because it can't find feature `"clippy` - Travis just parses the yml really weird. I fixed it in the end by running clippy through cargo. Though as a side note what would work is `env: FLAGS="--features clippy --features tokio"`

Resolved by #112
